### ISSUE TITLE
popper: violation to assume user has "make"

### ISSUE THREAD

**Issue by michaelsevilla** [noahdesu/zlog-popper#11]
In your experiment folder, you have a `Makefile` to pull the jupyer docker image and build the `.png`. Does this violate Popper because you're assuming the user has `make` installed on their computer?

Workarounds:
- include Docker container that has `make`
- change your `Makefile` to `graph.sh` or something similar

**Comment by dotnwat** [comment]
It isn't really possible to change Makefile to graph.sh because the entire purpose of the Makefiles is to track file modification times to avoid re-creating graphs. However, I could create graph.sh which started a docker container and ran make inside that. But, then I'd have to assume the user had bash installed haha

**Comment by michaelsevilla** [comment]
I think we need @ivotron's opinion on this one.

**Comment by dotnwat** [comment]
http://www.linuxfromscratch.org/

**Comment by ivotron** [comment]
I think both make and bash are reasonable assumptions, as long as we
specify that what versions we require.

**Comment by dotnwat** [comment]
I created a list of requirements. I'll add the versions in later. https://github.com/noahdesu/zlog-popper/blob/master/README.md
